from MonteFuncs cimport  MONTE
from MonteFuncs cimport  MONTEB
from MonteFuncs cimport  MONTEC
from MonteFuncs cimport  MONTET
from MonteFuncs cimport  MONTEBT
from MonteFuncs cimport  MONTECT
from MonteFuncs import  MONTE
from MonteFuncs import  MONTEB
from MonteFuncs import  MONTEC
from MonteFuncs import  MONTET
from MonteFuncs import  MONTEBT
from MonteFuncs import  MONTECT
